(function(){
const SUPABASE_URL='https://ajnwfanzvdrjzpgnduhx.supabase.co';
const SUPABASE_KEY='sb_publishable_m5aABZWO2OT6jQE8asfmpw_4c9ddAOj';
const TABLE_MAP={reviews:'site_reviews',orders:'site_orders',team:'team_members'};
const table=t=>TABLE_MAP[t]||t;
const ready=(async()=>{if(!window.supabase){await new Promise((r,j)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=r;s.onerror=j;document.head.appendChild(s)})}const c=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});window.__sharedSupabase=c;return c})();
window.__supabaseReady=ready;
const unpack=row=>row?Object.assign({},row.data||{},{id:row.id,created_at:row.created_at,updated_at:row.updated_at}):null;
window.getRows=async function(t){
  const c=await ready;
  if(t==='site_settings'){
    const {data,error}=await c.from('site_settings').select('*').order('key');
    if(error){console.error('Supabase getRows site_settings',error);return []}
    return data||[];
  }
  const {data,error}=await c.from(table(t)).select('id,data,created_at,updated_at').order('created_at',{ascending:true});
  if(error){console.error('Supabase getRows '+t,error);return []}
  return (data||[]).map(unpack);
};
window.insertRow=async function(t,obj){const c=await ready;if(t==='site_settings'){const {data,error}=await c.from('site_settings').upsert({key:obj.key,value:obj.value||{},updated_at:new Date().toISOString()},{onConflict:'key'}).select().single();if(error){console.error(error);return null}return data}const clean={...obj};delete clean.id;delete clean.created_at;delete clean.updated_at;const {data,error}=await c.from(table(t)).insert({data:clean}).select('id,data,created_at,updated_at').single();if(error){console.error('Supabase insertRow '+t,error);return null}return unpack(data)};
window.updateRow=async function(t,id,obj){const c=await ready;if(t==='site_settings'){const {data,error}=await c.from('site_settings').update({value:obj.value||{},updated_at:new Date().toISOString()}).eq('key',id).select().single();if(error){console.error(error);return null}return data}const clean={...obj};delete clean.id;delete clean.created_at;delete clean.updated_at;const {data,error}=await c.from(table(t)).update({data:clean,updated_at:new Date().toISOString()}).eq('id',id).select('id,data,created_at,updated_at').single();if(error){console.error('Supabase updateRow '+t,error);return null}return unpack(data)};
window.deleteRow=async function(t,id){const c=await ready;const {error}=await c.from(table(t)).delete().eq('id',id);if(error){console.error('Supabase deleteRow '+t,error);return false}return true};
window.getSetting=async function(key){const c=await ready;const {data,error}=await c.from('site_settings').select('value').eq('key',key).maybeSingle();if(error){console.error(error);return null}return data?data.value:null};
window.upsertSetting=async function(key,value){const c=await ready;const {data,error}=await c.from('site_settings').upsert({key,value,updated_at:new Date().toISOString()},{onConflict:'key'}).select().single();if(error){console.error(error);return null}return data};
const applySiteContent=async()=>{try{const c=await window.getSetting('siteContent')||{};const P=c.heroImage||'https://i.postimg.cc/zGjXyqgJ/1789666143836-removebg-preview.png';const A=c.aboutImage||'https://i.postimg.cc/rs7BS7xF/file-000000003d948207ac0d1ae3ccdc0cc7.png';const h=document.querySelector('.hero-text h1');if(h)h.innerHTML='<span class="hero-greeting">Hey I\'m</span><span class="hero-name">Mohammad Korim</span>';document.querySelectorAll('.hero-img img').forEach(i=>{i.src=P;i.removeAttribute('srcset')});const n=document.querySelector('nav .logo');if(n)n.innerHTML='<img class="md-nav-avatar" src="'+P+'" alt="MD Korim"><span class="md-nav-name">MD Korim</span>';const a=document.querySelector('.about-img');if(a){a.src=A;a.removeAttribute('srcset')}}catch(e){console.error(e)}};
const initDesign=()=>{if(document.body.dataset.mdDesign)return;document.body.dataset.mdDesign='1';const s=document.createElement('style');s.textContent=`nav .logo{display:flex!important;align-items:center!important;gap:8px!important}nav .logo .md-nav-avatar{width:34px!important;height:34px!important;border-radius:50%!important;object-fit:cover!important;border:2px solid var(--green)!important}nav .logo .md-nav-name{font-family:Poppins,sans-serif!important;font-size:1rem!important;font-weight:800!important;color:var(--green)!important}.hero-text h1{display:flex!important;flex-direction:column!important;align-items:flex-start!important;gap:3px!important;line-height:1.05!important}.hero-text h1 .hero-greeting{display:block!important;color:#fff!important;font-size:.7em!important;font-weight:500!important}.hero-text h1 .hero-name{display:block!important;color:#fff!important;font-size:.85em!important;font-weight:800!important}.hero-role-line,.hero-eyebrow{display:none!important}.hero-img{display:block!important;visibility:visible!important;opacity:1!important}.hero-img img{display:block!important;visibility:visible!important;opacity:1!important;width:auto!important;max-width:100%!important}footer{background:#1a7a3c!important;color:#fff!important}.my-blogs-link{font-weight:600!important}`;document.head.appendChild(s);const links=[...document.querySelectorAll('nav a,.nav-links a,.mobile-nav a')];if(!links.some(a=>['my blog','my blogs'].includes(a.textContent.trim().toLowerCase()))){const ul=document.querySelector('.nav-links');if(ul){const li=document.createElement('li');li.innerHTML='<a class="my-blogs-link" href="my-blogs.html">My Blogs</a>';ul.appendChild(li)}const mobile=document.querySelector('.mobile-nav');if(mobile){const a=document.createElement('a');a.className='my-blogs-link';a.href='my-blogs.html';a.textContent='My Blogs';mobile.appendChild(a)}}};
const refreshUserData=async()=>{try{if(typeof window.renderHomeServices==='function')window.renderHomeServices();if(typeof window.renderHomePortfolio==='function')window.renderHomePortfolio();if(typeof window.renderHomeReviews==='function')window.renderHomeReviews();if(typeof window.renderTeam==='function')window.renderTeam()}catch(e){console.error('MD Korim user data refresh failed',e)}};
ready.then(async()=>{initDesign();await applySiteContent();if(document.readyState!=='loading')refreshUserData();window.dispatchEvent(new CustomEvent('mdkorim-supabase-ready'));}).catch(console.error);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{initDesign();refreshUserData()});
})();